### ISSUE TITLE
Chevron icons: multiple elements having same id should be avoided 

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-css-workflow-icons#27]
Following `id` declaration results in aXe error on React-Spectrum documentation pages, like https://react-spectrum.adobe.com/react-spectrum/ActionButton.html#props,  because the same icon is reused in several places on the page to indicate the expanded or collapsed state of details/summary elements.

- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronRight.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronLeft.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronDoubleRight.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronDoubleRight.js#L36
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronDoubleRight.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronDoubleLeft.js#L36
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronUp.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronDown.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronUpDown.js#L31
- https://github.com/adobe/spectrum-css-workflow-icons/blob/81b7780991a48237d35c4a2ecf035d17bfe39429/dist/react-spectrum-workflow/dist/ChevronUpDown.js#L36

**Comment by jianliao** [comment]
@majornista @snowystinger [@adobe/react-spectrum-workflow@2.3.4](https://www.npmjs.com/package/@adobe/react-spectrum-workflow) released. Please verify and close this issue if it works.
